export {default as Navbar} from "./Navbar"
export {default as Sidebar} from "./Sidebar"
export {default as root} from "./root"
export {default as AnimeCard} from "./AnimeCard"
export {default as AnimeDetails} from "./AnimeDetails"
export {default as Genre} from "./Genre"
